/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#include "DIALOG.h"
#include "GUI.h"
#include "MainTask.h"
#include "FramewinDLG.h"

#include "GUIFont_Create.h"


/* FreeRTOS头文件 */
#include "FreeRTOS.h"
#include "task.h"

#include <stdio.h>
#include <string.h>


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/


// USER START (Optionally insert additional defines)
extern const char Framewin_text[];
extern char XianGao_MODE[];
extern char GuanBi_MODE[];
extern char Set_MODE[];
extern char More_MODE[];
extern char text[];
extern char MULTIEDIT_text[];
extern char *BUTTON_text[];

extern WM_HWIN Create_XianGao_Sure_Window(void);//设备将调整为限高模式……
extern WM_HWIN Create_PARAMETERS_SET_Framewin(void);//参数设置
extern WM_HWIN Create_MoreInformation_Framewin(void);//更多……

// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_HOMEPAGE_FRAMEWIN, 0, 0, 480, 320, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button", ID_XIANGAO_MODE_BUTTON, 22, 60, 90, 160, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_JINXING_MODE_BUTTON, 136, 60, 90, 160, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_CANSHU_SET_BUTTON, 250, 60, 90, 160, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_GENGDUO_BUTTON, 363, 60, 90, 160, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_LOGO_TEXT, 140, 251, 320, 26, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
		BUTTON_SKINFLEX_PROPS BUTTON_Props;
   FRAMEWIN_SKINFLEX_PROPS Framewin_Props;
  // USER START (Optionally insert additional variables)
	WM_HWIN hDlg;
	hDlg = pMsg->hWin;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Framewin'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetText(hItem, Framewin_text);
	  FRAMEWIN_SetFont(hItem,&XBF_Font24);
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetTitleHeight(hItem, 35);
	
		/* 获取激活状态下框架窗口的皮肤参数 */
			FRAMEWIN_GetSkinFlexProps(&Framewin_Props, FRAMEWIN_SKINFLEX_PI_ACTIVE);
			Framewin_Props.aColorFrame[1] = GUI_RED;
			Framewin_Props.aColorFrame[2] = 0xFFF5C3;
			Framewin_Props.aColorTitle[0] = 0xFFF5C3;
			Framewin_Props.aColorTitle[1] = 0x9452A5;			
			Framewin_Props.Radius = 0;
			/* 设置框架创建激活状态下的皮肤 */
			FRAMEWIN_SetSkinFlexProps(&Framewin_Props, FRAMEWIN_SKINFLEX_PI_ACTIVE);
			/* 设置框架创建未激活状态下的皮肤 */
		//	FRAMEWIN_SetSkinFlexProps(&Framewin_Props, FRAMEWIN_SKINFLEX_PI_INACTIVE);
	
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_XIANGAO_MODE_BUTTON);
    BUTTON_SetFont(hItem, &XBF_Font24);
    BUTTON_SetText(hItem, XianGao_MODE);
	
			/* 获取按钮启动状态的皮肤 */
		//	BUTTON_GetSkinFlexProps(&BUTTON_Props, BUTTON_SKINFLEX_PI_ENABLED);
			BUTTON_Props.aColorFrame[0] = GUI_GREEN;
			BUTTON_Props.aColorFrame[1] = GUI_GREEN;
			BUTTON_Props.aColorFrame[2] = GUI_GREEN;

			BUTTON_Props.aColorLower[0] = 0x5efce8;
			BUTTON_Props.aColorLower[1] = 0x736EFE;
			
			BUTTON_Props.aColorUpper[0] = 0x736EFE;
			BUTTON_Props.aColorUpper[1] = 0x5efce8;

			/* 设置按下启动状态的皮肤色 */
		//	BUTTON_SetSkinFlexProps(&BUTTON_Props, BUTTON_SKINFLEX_PI_ENABLED);
			/* 设置聚焦状态的皮肤色 */
			BUTTON_SetSkinFlexProps(&BUTTON_Props, BUTTON_SKINFLEX_PI_FOCUSSED);

//			BUTTON_Props.aColorFrame[0] = 0x8708cc;
//			BUTTON_Props.aColorFrame[1] = 0x8708cc;
//			BUTTON_Props.aColorFrame[2] = 0x8708cc;

//			BUTTON_Props.aColorLower[0] = 0x8708cc;
//			BUTTON_Props.aColorLower[1] = 0x8708cc;
//			
//			BUTTON_Props.aColorUpper[0] = 0x8708cc;
//			BUTTON_Props.aColorUpper[1] = 0x8708cc;
			/* 设置按下状态的皮肤色 */
			//BUTTON_SetSkinFlexProps(&BUTTON_Props, BUTTON_SKINFLEX_PI_PRESSED);
	
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_JINXING_MODE_BUTTON);
    BUTTON_SetFont(hItem, &XBF_Font24);
	  BUTTON_SetText(hItem, GuanBi_MODE);
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_CANSHU_SET_BUTTON);
    BUTTON_SetText(hItem, Set_MODE);
    BUTTON_SetFont(hItem, &XBF_Font24);
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_GENGDUO_BUTTON);
    BUTTON_SetFont(hItem, &XBF_Font24);
    BUTTON_SetText(hItem, More_MODE);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_LOGO_TEXT);
    TEXT_SetFont(hItem, &XBF_Font24);
		TEXT_SetText(hItem, text);
		//TEXT_SetTextColor(hItem, GUI_WHITE);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
//		case WM_PAINT:
////			/* 重绘消息处理，重绘背景色并显示一条红色直线 */
//			
//			GUI_SetBkColor(GUI_RED);
//			GUI_Clear();
//		//	GUI_SetBkColor(0xABDCFF);
//		// GUI_DrawGradientRoundedH(0, 50, 300, 100, 1,0xff0000,0x00ffff);
//		//	GUI_Clear();
////		  GUI_SetColor(GUI_RED);
////			GUI_DrawLine(35, 10, 185, 10);
//		// hItem = pMsg->hWin;
//		 //QR_Code_Drawing(QR_TEXT, 5, GUI_QR_ECLEVEL_L, 240, 90);
//	  // WM_InvalidateWindow(WM_HBKWIN);
//		break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_XIANGAO_MODE_BUTTON: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			  GUI_EndDialog(hDlg, 1);
		  	Create_XianGao_Sure_Window();
			//	CreateFramewin3();
			 // WM_SetFocus(CreateFramewin3());
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_JINXING_MODE_BUTTON: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_CANSHU_SET_BUTTON: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		  	GUI_EndDialog(hDlg, 1);
				Create_PARAMETERS_SET_Framewin();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_GENGDUO_BUTTON: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			  GUI_EndDialog(hDlg, 1);
				Create_MoreInformation_Framewin();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END	
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN Create_Homepage_Framewin(void);
WM_HWIN Create_Homepage_Framewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)

// USER END

/*************************** End of file ****************************/
