/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#include "DIALOG.h"
#include "GUI.h"
#include "MainTask.h"
#include "led/bsp_led.h"
#include "FramewinDLG.h"

#include "GUIFont_Create.h"
#include "led/bsp_led.h"

/* FreeRTOS头文件 */
#include "FreeRTOS.h"
#include "task.h"

#include <stdio.h>
#include <string.h>
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/


#define MSG_CHANGE_TEXT_1 (WM_USER + 1)

// USER START (Optionally insert additional defines)
static const char QR_TEXT[] = "http://www.xitaihua.com.cn";
extern const char MoreInformation_text[];

extern WM_HWIN Create_Homepage_Framewin(void);
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate3[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_MoreInformation_FRAMEWIN, 1, 0, 480, 320, WM_CF_MEMDEV, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_MoreInformation_TEXT, 50, 100, 190, 100, 0, 0x64, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_BuckHome_BUTTON, 380, 275, 80, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
/**
  * @brief Button1控件回调函数
  * @note 无
  * @param pMsg：消息指针：消息指针
  * @retval 无
  */
//static void _cbButton0(WM_MESSAGE* pMsg)
//{
//	GUI_RECT Rect;

//	switch (pMsg->MsgId)
//	{
//	case WM_PAINT:
//	//QR_Code_Drawing(QR_TEXT, 5, GUI_QR_ECLEVEL_Q, 230, 85);	
//		WM_GetClientRect(&Rect);
//		if (BUTTON_IsPressed(pMsg->hWin))
//		{
//			QR_Code_Drawing(QR_TEXT, 5, GUI_QR_ECLEVEL_Q, 230, 85);
////			GUI_SetColor(GUI_GRAY_C8);
////			GUI_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 10);
////			GUI_SetBkColor(GUI_GRAY_C8);
////			GUI_SetColor(0xA0ECECEC);
////			GUI_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 10);
//		}
//		else
//		{
//			QR_Code_Drawing(QR_TEXT, 5, GUI_QR_ECLEVEL_Q, 230, 85);
////			GUI_SetColor(GUI_WHITE);
////			GUI_FillRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 10);
////			GUI_SetBkColor(GUI_WHITE);
////			GUI_SetColor(0xA0ECECEC);
////			GUI_DrawRoundedRect(Rect.x0, Rect.y0, Rect.x1, Rect.y1, 10);
//		}
////		GUI_SetColor(GUI_BLACK);
////		GUI_SetFont(&GUI_Font20B_ASCII);
////		GUI_DispStringInRect("Button1", &Rect, GUI_TA_HCENTER | GUI_TA_VCENTER);
//		break;

//	default:
//		BUTTON_Callback(pMsg);
//	}
//}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog3(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	WM_HWIN hDlg3;
	hDlg3 = pMsg->hWin;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Framewin'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTitleVis(hItem, 0);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_MoreInformation_TEXT);
  	TEXT_SetText(hItem, MoreInformation_text);
    TEXT_SetFont(hItem, &XBF_Font24);
	  TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x000000FF));
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
	 // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BuckHome_BUTTON);
	//  WM_SetCallback(hItem, _cbButton0);
    BUTTON_SetFont(hItem, GUI_FONT_16_ASCII);
    BUTTON_SetText(hItem, "Cancel");
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
		case WM_PAINT:
//			/* 重绘消息处理，重绘背景色并显示一条红色直线 */
//			GUI_SetBkColor(0xc0c0c0);
//			GUI_Clear();
//		  GUI_SetColor(GUI_RED);
//			GUI_DrawLine(35, 10, 185, 10);
		// hItem = pMsg->hWin;
		 QR_Code_Drawing(QR_TEXT, 5, GUI_QR_ECLEVEL_L, 240, 90);
	  // WM_InvalidateWindow(WM_HBKWIN);
		break;
	  case WM_KEY:
				switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
				{ 
					case GUI_KEY_ESCAPE:
								LED1_TOGGLE;
								GUI_EndDialog(hDlg3, 0);
							//	Create_Homepage_Framewin();
					     WM_SetFocus(WM_GetDialogItem(WM_GetClientWindow(Create_Homepage_Framewin()),ID_GENGDUO_BUTTON));
								break;
//		
////						case GUI_KEY_ENTER:
////								GUI_EndDialog(hDlg, 0);
////								break;
				}
					break;
		case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BuckHome_BUTTON: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
		   //	GUI_EndDialog(hDlg3, 0);
			//	CreateFramewin();
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
		}
      break;
			case MSG_CHANGE_TEXT_1:
				LED2_TOGGLE;
//			  GUI_EndDialog(hDlg3, 0);
//        CreateFramewin();
				//WM_InvalidateWindow(hDlg3);
				
			break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN Create_MoreInformation_Framewin(void);
WM_HWIN Create_MoreInformation_Framewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate3, GUI_COUNTOF(_aDialogCreate3), _cbDialog3, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)

//自定义消息函数
void _ChangeInfoText4()//char * pStr
{
	//GUI_HWIN Thim;
 // WM_MESSAGE Message;
  //Thim= WM_GetParent(CreateFramewin());
  //Message.MsgId  = MSG_CHANGE_TEXT_1;
  //Message.Data.p = pStr;
  //WM_SendMessage(WM_HBKWIN, &Message);
	//WM_SendMessageNoPara(WM_GetClientWindow(CreateFramewin3()),MSG_CHANGE_TEXT_1); 
  //WM_InvalidateWindow(WM_HBKWIN);
}
// USER END

/*************************** End of file ****************************/
