/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END
#include "DIALOG.h"
#include "GUI.h"
#include "MainTask.h"
#include "FramewinDLG.h"

#include "GUIFont_Create.h"


/* FreeRTOS头文件 */
#include "FreeRTOS.h"
#include "task.h"

#include <stdio.h>
#include <string.h>
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/


//#define ID_BUTTON_2   (GUI_ID_USER + 0x04)

// USER START (Optionally insert additional defines)

extern WM_HWIN Create_Homepage_Framewin(void);
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate2[] = {
  { FRAMEWIN_CreateIndirect, "Framewin", ID_PARAMETERS_SET_FRAMEWIN, 30, 30, 420, 260, 0, 0x64, 0 },
  { SPINBOX_CreateIndirect, "Spinbox", ID_DAOMIAN_HIGH_SET_SPINBOX, 175, 15, 140, 50, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_DAOMIAN_HIGH_SET_TEXT, 15, 15, 145, 50, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_DAOMIAN_HIGH_UNIT_TEXT, 330, 15, 60, 50, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_XIANGAO_HIGH_SET_EDIT, 175, 85, 140, 50, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_XIANGAO_HIGH_SET_TEXT, 15, 85, 145, 50, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_XIANGAO_HIGH_UNIT_TEXT, 330, 85, 60, 50, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_JINXING_HIGH_SET_TEXT, 15, 155, 145, 50, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "Text", ID_JINXING_HIGH_SET_UNIT, 330, 155, 60, 50, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Edit", ID_JINXING_HIGH_SET_EDIT, 175, 155, 140, 50, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog2(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	WM_HWIN hDlg;
	hDlg = pMsg->hWin;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Framewin'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetText(hItem, "参数设置");
  	FRAMEWIN_SetFont(hItem, &XBF_Font24);
    FRAMEWIN_SetTitleHeight(hItem, 30);
    //
    // Initialization of 'Spinbox'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DAOMIAN_HIGH_SET_SPINBOX);
    SPINBOX_SetFont(hItem,  &XBF_Font24);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DAOMIAN_HIGH_SET_TEXT);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "岛面高度设置");
    TEXT_SetFont(hItem,  &XBF_Font24);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_DAOMIAN_HIGH_UNIT_TEXT);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "m");
    TEXT_SetFont(hItem,  &XBF_Font24);
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_XIANGAO_HIGH_SET_EDIT);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem,  &XBF_Font24);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_XIANGAO_HIGH_SET_TEXT);
    TEXT_SetText(hItem, "限高高度设置");
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetFont(hItem,  &XBF_Font24);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_XIANGAO_HIGH_UNIT_TEXT);
    TEXT_SetText(hItem, "m");
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem,  &XBF_Font24);
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_JINXING_HIGH_SET_TEXT);
    TEXT_SetFont(hItem,  &XBF_Font24);
    TEXT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
    TEXT_SetText(hItem, "禁行高度设置");
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_JINXING_HIGH_SET_UNIT);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetFont(hItem,  &XBF_Font24);
    TEXT_SetText(hItem, "m");
    //
    // Initialization of 'Edit'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_JINXING_HIGH_SET_EDIT);
    EDIT_SetText(hItem, "123");
    EDIT_SetFont(hItem,  &XBF_Font24);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
		
		 case WM_KEY:
					switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
					{ 
			      case GUI_KEY_ESCAPE:
									GUI_EndDialog(hDlg, 1);
									//CreateFramewin();
						      WM_SetFocus(WM_GetDialogItem(WM_GetClientWindow(Create_Homepage_Framewin()),ID_CANSHU_SET_BUTTON));
									break;
			
//						case GUI_KEY_ENTER:
//									GUI_EndDialog(hDlg, 0);
//									break;
					}
					break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_DAOMIAN_HIGH_SET_SPINBOX: // Notifications sent by 'Spinbox'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_MOVED_OUT:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_XIANGAO_HIGH_SET_EDIT: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_JINXING_HIGH_SET_EDIT: // Notifications sent by 'Edit'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN Create_PARAMETERS_SET_Framewin(void);
WM_HWIN Create_PARAMETERS_SET_Framewin(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate2, GUI_COUNTOF(_aDialogCreate2), _cbDialog2, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
