/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "GUI.h"
#include "MainTask.h"

#include "GUIFont_Create.h"


/* FreeRTOS头文件 */
#include "FreeRTOS.h"
#include "task.h"

#include <stdio.h>
#include <string.h>
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
//#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
//#define ID_IMAGE_0 (GUI_ID_USER + 0x02)
#define ID_TEXT_0   (GUI_ID_USER + 0x01)
#define ID_TEXT_1   (GUI_ID_USER + 0x02)
#define ID_MULTIEDIT_0   (GUI_ID_USER + 0x03)
#define ID_BUTTON_0   (GUI_ID_USER + 0x04)
#define ID_BUTTON_1   (GUI_ID_USER + 0x05)

#define ID_IMAGE_0_IMAGE_0  0x00

// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/
extern const char Framewin_text[];
extern const char text[];
extern const char MULTIEDIT_text[];
extern const char *BUTTON_text[];


/*********************************************************************
*
*       _acImage_0, "BMP", ID_IMAGE_0_IMAGE_0
*/
//static const U8 _acImage_0[463] = {
//  0x42, 0x4D, 0xCE, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3E, 0x00, 0x00, 0x00, 0x28, 0x00, 0x00, 0x00, 0x32, 0x00, 0x00, 0x00, 0x32, 0x00, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x90, 0x01, 0x00, 0x00, 0x12, 0x0B, 0x00, 0x00,
//  0x12, 0x0B, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21,
//  0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00,
//  0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84,
//  0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08,
//  0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10,
//  0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00,
//  0x88, 0x42, 0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42,
//  0x10, 0x84, 0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84,
//  0x21, 0x08, 0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0x88, 0x42, 0x10, 0x84, 0x21, 0x08,
//  0x40, 0x00, 0x84, 0x21, 0x08, 0x42, 0x10, 0x84, 0x40, 0x00, 0xC2, 0x10, 0x84, 0x21, 0x08, 0x42, 0x40, 0x00, 0xA1, 0x08, 0x42, 0x10, 0x84, 0x21, 0x40, 0x00, 0x90, 0x84, 0x21, 0x08, 0x42, 0x10, 0xC0, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xC0, 0x00,
//  0x00,
//};

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
//static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
//  { FRAMEWIN_CreateIndirect, Framewin_text, ID_FRAMEWIN_0, 0, 0, 480, 320, 0, 0x0, 0 },
//  //{ BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 56, 79, 80, 20, 0, 0x0, 0 },
//  //{ IMAGE_CreateIndirect, "Image", ID_IMAGE_0, 17, 12, 50, 50, 0, 0, 0 },
//  // USER START (Optionally insert additional widgets)
//  // USER END
//};

//static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
//    { FRAMEWIN_CreateIndirect,  "硬石电子",             0,             0, 0,   320,480,FRAMEWIN_CF_MOVEABLE,0},
//    { TEXT_CreateIndirect,      "硬石电子",        GUI_ID_TEXT0,     0, 30, 80, 20, 0, 0x0, 0},
//    { TEXT_CreateIndirect,      "硬石电子",        GUI_ID_TEXT1,     0, 120, 180, 150, 0, 0x0, 0},
//    { TEXT_CreateIndirect,      "硬石电子",        GUI_ID_TEXT2,     0, 240, 320, 320, 0, 0x0, 0},
//};


static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect," Framewin_text", ID_FRAMEWIN_0, 0, 0, 480, 320, 0, 0x0, 0 },
	//{ TEXT_CreateIndirect, "Text", ID_TEXT_0, 0, 35, 440, 70, 0, 0x0, 0 },
  //{ TEXT_CreateIndirect, "Text", ID_TEXT_1, 20, 110, 440, 120, 0, 0x64, 0 },
 // { MULTIEDIT_CreateIndirect, "Multiedit", ID_MULTIEDIT_0, 20, 240, 440, 130, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_1, 20, 220, 140, 36, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Button", ID_BUTTON_0, 300, 220, 140, 36, 0, 0x0, 0 },
};
/*********************************************************************
*
*       Static code
*
**********************************************************************
*/
/*********************************************************************
*
*       _GetImageById
*/
//static const void * _GetImageById(U32 Id, U32 * pSize) {
//  switch (Id) {
//  case ID_IMAGE_0_IMAGE_0:
//    *pSize = sizeof(_acImage_0);
//    return (const void *)_acImage_0;
//  }
//  return NULL;
//}

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
//static void _cbDialog(WM_MESSAGE * pMsg) {
//  const void * pData;
//  WM_HWIN      hItem;
//  U32          FileSize;
//  int          NCode;
//  int          Id;
//  // USER START (Optionally insert additional variables)
//  // USER END

//  switch (pMsg->MsgId) {
//  case WM_INIT_DIALOG:
//    //
//    // Initialization of 'Framewin'
//    //
//    hItem = pMsg->hWin;
//  	WM_HWIN hWin = pMsg->hWin;
//    FRAMEWIN_SetFont(hWin,  &XBF_Font16);
//    //FRAMEWIN_SetText(hWin, Framewin_text);
// 
//    FRAMEWIN_SetTitleHeight(hWin, 35);
//    FRAMEWIN_SetTextAlign(hWin, GUI_TA_HCENTER | GUI_TA_VCENTER);
//    //
//    // Initialization of 'Image'
//    //
////    hItem = WM_GetDialogItem(pMsg->hWin, ID_IMAGE_0);
////    pData = _GetImageById(ID_IMAGE_0_IMAGE_0, &FileSize);
////    IMAGE_SetBMP(hItem, pData, FileSize);
//    // USER START (Optionally insert additional code for further widget initialization)
//    // USER END
//    break;
//  case WM_NOTIFY_PARENT:
//    Id    = WM_GetId(pMsg->hWinSrc);
//    NCode = pMsg->Data.v;
//    switch(Id) {
//    case ID_BUTTON_0: // Notifications sent by 'Button'
//      switch(NCode) {
//      case WM_NOTIFICATION_CLICKED:
//        // USER START (Optionally insert code for reacting on notification message)
//        // USER END
//        break;
//      case WM_NOTIFICATION_RELEASED:
//        // USER START (Optionally insert code for reacting on notification message)
//        // USER END
//        break;
//      // USER START (Optionally insert additional code for further notification handling)
//      // USER END
//      }
//      break;
//    // USER START (Optionally insert additional code for further Ids)
//    // USER END
//    }
//    break;
//  // USER START (Optionally insert additional message handling)
//  // USER END
//  default:
//    WM_DefaultProc(pMsg);
//    break;
//  }
//}


/**
  * @brief 对话框回调函数
  * @note 无
  * @param pMsg：消息指针
  * @retval 无
 */ 
static void _cbDialog(WM_MESSAGE * pMsg)
{
  WM_HWIN hItem;
  int     NCode;
  int     Id;

  switch (pMsg->MsgId)
	{
	  case WM_PAINT:
           // PaintDialog(pMsg);
            break;
		case WM_INIT_DIALOG:
			/* 初始化Framewin控件 */
		hItem = pMsg->hWin;
		//  WM_HWIN hWin = pMsg->hWin;
  FRAMEWIN_SetFont(hItem,&XBF_Font24);
	FRAMEWIN_SetText(hItem, Framewin_text);
 // FRAMEWIN_SetTextAlign(hItem,GUI_TA_VCENTER|GUI_TA_CENTER);
  //FRAMEWIN_AddCloseButton(hWin, FRAMEWIN_BUTTON_RIGHT, 0);
  //FRAMEWIN_AddMaxButton(hWin, FRAMEWIN_BUTTON_RIGHT, 1);
 // FRAMEWIN_AddMinButton(hWin, FRAMEWIN_BUTTON_RIGHT, 2);
  FRAMEWIN_SetTitleHeight(hItem,35);
//			hItem = pMsg->hWin;
//			FRAMEWIN_SetTitleHeight(hItem, 100);
//		  FRAMEWIN_SetFont(hItem, &XBF_Font16);
//			FRAMEWIN_SetText(hItem, "安徽西天话");
			
			/* 初始化TEXT0 */
//			hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
//			 TEXT_SetText(hItem, text);
//			TEXT_SetFont(hItem, &XBF_Font24);	//GUI_Font24_ASCII
//		  
////			/* 初始化TEXT1 */
//		hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
//			TEXT_SetText(hItem, MULTIEDIT_text);
//			TEXT_SetFont(hItem, &XBF_Font24);
//			/* 初始化MULTIEDIT0 */
//			hItem = WM_GetDialogItem(pMsg->hWin, ID_MULTIEDIT_0);
//			MULTIEDIT_SetReadOnly(hItem, 1);
//			MULTIEDIT_SetBufferSize(hItem, 200);
//			MULTIEDIT_SetWrapWord(hItem);
//			MULTIEDIT_SetText(hItem, MULTIEDIT_text);
//			MULTIEDIT_SetFont(hItem, &XBF_Font24);
//			MULTIEDIT_SetTextColor(hItem, MULTIEDIT_CI_READONLY, GUI_GREEN);
//			MULTIEDIT_SetBkColor(hItem, MULTIEDIT_CI_READONLY, GUI_BLACK);
//			MULTIEDIT_ShowCursor(hItem, 0);
			/* 初始化Button0 */
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
			BUTTON_SetFont(hItem, &XBF_Font24);
			BUTTON_SetText(hItem, BUTTON_text[0]);
			/* 初始化Button1 */
			hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
			BUTTON_SetFont(hItem, &XBF_Font24);
			BUTTON_SetText(hItem, BUTTON_text[1]);
			break;
		case WM_NOTIFY_PARENT:
			Id    = WM_GetId(pMsg->hWinSrc);
			NCode = pMsg->Data.v;
			switch(Id)
			{
				case ID_MULTIEDIT_0: // Notifications sent by 'Multiedit'
					switch(NCode)
					{
						case WM_NOTIFICATION_CLICKED:
							break;
						case WM_NOTIFICATION_RELEASED:
							break;
						case WM_NOTIFICATION_VALUE_CHANGED:
							break;
					}
					break;
				case ID_BUTTON_0: // Notifications sent by 'Button'
					switch(NCode)
					{
						case WM_NOTIFICATION_CLICKED:
							break;
						case WM_NOTIFICATION_RELEASED:
							break;
					}
					break;
				case ID_BUTTON_1: // Notifications sent by 'Button'
					switch(NCode)
					{
						case WM_NOTIFICATION_CLICKED:
							break;
						case WM_NOTIFICATION_RELEASED:
							break;
					}
					break;
			}
			break;
		default:
			WM_DefaultProc(pMsg);
			break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateFramewin
*/
WM_HWIN CreateFramewin(void);
WM_HWIN CreateFramewin(void) {
  WM_HWIN hWin;
 hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
 // hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
