/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "GUI.h"
#include "MainTask.h"
#include "FramewinDLG.h"

#include "GUIFont_Create.h"


/* FreeRTOS头文件 */
#include "FreeRTOS.h"
#include "task.h"

#include <stdio.h>
#include <string.h>
/*********************************************************************
*
*       Defines
*
**********************************************************************
*/

extern const char *BUTTON_text[];
extern const char XianGao_QR_text[];
extern const char XianGao_GC_text[];
static const GUI_POINT _aPointArrow[] = {
  {240,  45 },
  {170, 155 },
  {310, 155 },
};

extern WM_HWIN Create_Homepage_Framewin(void);
extern WM_HWIN Create_XianGao_Process_Window(void);
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_XianGao_Sure_WINDOW, 10, 10, 460, 300, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Text", ID_XianGao_Sure_TEXT, 55, 165, 400, 50, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Button", ID_XianGao_Sure_BUTTON, 365, 260, 80, 30, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
	WM_HWIN hWinOld;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	WM_HWIN hDlg;
	hDlg = pMsg->hWin;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_XianGao_Sure_TEXT);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, GUI_BLACK);
    TEXT_SetFont(hItem, &XBF_Font24);
    TEXT_SetText(hItem, XianGao_QR_text);
    //
    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_XianGao_Sure_BUTTON);
    BUTTON_SetText(hItem, BUTTON_text[0]);
    BUTTON_SetFont(hItem, &XBF_Font24);
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
    break;
			case WM_PAINT:
//			/* 重绘消息处理，重绘背景色并显示一条红色直线 */
			GUI_SetBkColor(0xc0c0c0);
			GUI_Clear();
			
			GUI_SetPenSize(3);
		  GUI_SetColor(GUI_RED);
		//	GUI_DrawLine(35, 10, 185, 10);
			GUI_DrawPolygon(_aPointArrow, 3, 0,0);
			GUI_DrawGradientRoundedV(232,65,248,125,5,0x0000FF, 0xFF0000);
			GUI_SetColor(GUI_RED);
			GUI_FillCircle(240,142,8);
		// hItem = pMsg->hWin;
		// QR_Code_Drawing(QR_TEXT, 5, GUI_QR_ECLEVEL_L, 0, 0);
	  // WM_InvalidateWindow(WM_HBKWIN);
		break;
	  case WM_KEY:
				switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
				{ 
					case GUI_KEY_ESCAPE:
								//LED1_TOGGLE;
								GUI_EndDialog(hDlg, 0);
								//CreateFramewin();
								WM_SetFocus(WM_GetDialogItem(WM_GetClientWindow(Create_Homepage_Framewin()),ID_XIANGAO_MODE_BUTTON));
								break;
//		
////						case GUI_KEY_ENTER:
////								GUI_EndDialog(hDlg, 0);
////								break;
				}
					break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_XianGao_Sure_BUTTON: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
//					hWinOld = WM_SelectWindow(WM_GetClientWindow(pMsg->hWin));
//					hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
//		    	WM_InvalidateWindow(hItem);
//					GUI_SetBkColor(0xc0c0c0);
//					GUI_Clear();
//			
//				  GUI_SetColor(GUI_BLACK);
//					GUI_SetFont(&XBF_Font24);
//					GUI_DispStringHCenterAt(XianGao_GC_text, 230, 150);
//		    	WM_SelectWindow(hWinOld);
			GUI_EndDialog(hDlg, 0);
			Create_XianGao_Process_Window();
			// USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN Create_XianGao_Sure_Window(void);
WM_HWIN Create_XianGao_Sure_Window(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
