/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "GUI.h"
#include "MainTask.h"
#include "FramewinDLG.h"

#include "GUIFont_Create.h"


/* FreeRTOS头文件 */
#include "FreeRTOS.h"
#include "task.h"

#include <stdio.h>
#include <string.h>

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/


#define MSG_CHANGE_KEY (GUI_ID_USER + 0x1C)
#define MSG_CHANGE_KEY1 (GUI_ID_USER + 0x1d)

extern const char XianGao_GC_text[];
extern const char MULTIEDIT_text[];
extern const char *BUTTON_text[];
//extern WM_HWIN CreateFramewin(void);

//extern WM_HWIN CreateWindow(void);

//extern void _cbBkWindow(WM_MESSAGE* pMsg);
WM_HWIN Create_XianGao_Process_Window(void);

extern WM_HWIN Create_Homepage_Framewin(void);
// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_XianGao_Process_WINDOW, 10, 10, 460, 300, 0, 0x0, 0 },
	{ BUTTON_CreateIndirect, "Button", ID_XianGao_Process_BUTTON, 190, 256, 100, 30, 0, 0x0, 0 },
 // { TEXT_CreateIndirect, "Text", ID_TEXT_0, 85, 121, 300, 50, 0, 0x64, 0 },
 // USER START (Optionally insert additional widgets)
 // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)

static void _cbButton2(WM_MESSAGE* pMsg)
{
		WM_HWIN hWinOld;
//		WM_HWIN hDlg;
//	  int     NCode;
//  int     Id;
//	hDlg = pMsg->hWin;
	switch (pMsg->MsgId)
	{
	case WM_PAINT:
		      hWinOld = WM_SelectWindow(WM_GetClientWindow(pMsg->hWin));
					//	hWinOld = WM_SelectWindow(WM_HBKWIN);
					GUI_SetBkColor(0xc0c0c0);
	
					GUI_Clear();
			
				  GUI_SetColor(GUI_BLACK);
					GUI_SetFont(&XBF_Font24);
					GUI_DispStringHCenterAt(MULTIEDIT_text, 230, 150);
	        //WM_InvalidateWindow(pMsg->hWin);
		    	WM_SelectWindow(hWinOld);
	WM_InvalidateWindow(pMsg->hWin);
		break;
	default:
		BUTTON_Callback(pMsg);
	}
}
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
	WM_HWIN hWinOld;
	  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
	WM_HWIN hDlg;
	hDlg = pMsg->hWin;
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'Text'
    //
//    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
//    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
//    TEXT_SetFont(hItem, &XBF_Font24);
//    TEXT_SetText(hItem, XianGao_GC_text);
//    TEXT_SetTextColor(hItem, GUI_MAKE_COLOR(0x00000000));
    // USER START (Optionally insert additional code for further widget initialization)
    // USER END
	    // Initialization of 'Button'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_XianGao_Process_BUTTON);
    BUTTON_SetFont(hItem, &XBF_Font24);
    BUTTON_SetText(hItem, BUTTON_text[1]);
    break;
  // USER START (Optionally insert additional message handling)
		case WM_PAINT:
			/* 重绘消息处理*/
			GUI_SetBkColor(0xc0c0c0);
			GUI_Clear();
		  GUI_SetColor(GUI_BLACK);
			GUI_SetFont(&XBF_Font24);
			GUI_DispStringHCenterAt(XianGao_GC_text, 230, 150);
			break;

		case WM_NOTIFY_PARENT:
     Id    = WM_GetId(pMsg->hWinSrc);
     NCode = pMsg->Data.v;
     switch(Id) {
     case ID_XianGao_Process_BUTTON: // Notifications sent by 'Button'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
			//		GUI_EndDialog(hDlg, 0);
			//	Create_Homepage_Framewin();
			//		WM_SetFocus(WM_GetDialogItem(WM_GetClientWindow(Create_Homepage_Framewin()),ID_XIANGAO_MODE_BUTTON));
				
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
		}
      break;
			case WM_KEY:
				switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
				{ 
					case GUI_KEY_ESCAPE:
//								//LED1_TOGGLE;
								GUI_EndDialog(hDlg, 0);
					      WM_SetFocus(WM_GetDialogItem(WM_GetClientWindow(Create_Homepage_Framewin()),ID_XIANGAO_MODE_BUTTON));
//								CreateFramewin();
//								break;
////		
//////						case GUI_KEY_ENTER:
//////								GUI_EndDialog(hDlg, 0);
//////								break;
				}
					break;	
	case MSG_CHANGE_KEY:
					//	GUI_EndDialog(hDlg, 1);
        //	WM_SelectWindow(WM_HBKWIN);
	       // WM_InvalidateWindow(pMsg->hWin);
			  	WM_SetCallback(WM_GetClientWindow(pMsg->hWin), _cbButton2);
//					hWinOld = WM_SelectWindow(WM_GetClientWindow(pMsg->hWin));
//					GUI_SetBkColor(0xc0c0c0);
//					GUI_Clear();
//			
//				  GUI_SetColor(GUI_BLACK);
//					GUI_SetFont(&XBF_Font24);
//					GUI_DispStringHCenterAt(MULTIEDIT_text, 230, 150);
//		    	WM_SelectWindow(hWinOld);
		break;
	case MSG_CHANGE_KEY1:
//		 Id    = WM_GetId(pMsg->hWinSrc);
//    // NCode = pMsg->Data.v;
//	   if(Id==ID_WINDOW_1)
//		 {
//			GUI_EndDialog(hDlg, 0);
//			CreateFramewin(); 
//		 }
		//hWinOld=WM_GetClientWindow(pMsg->hWin);
		//GUI_EndDialog(hWinOld, 0);
  	//GUI_EndDialog(CreateWindow(),0);
	
	  //WM_DeleteWindow(hDlg);
  	//CreateFramewin();
	  // WM_SetCallback(WM_HBKWIN, _cbBkWindow);
	
	  break;
  // USER END
//		  case WM_KEY:
//				switch (((WM_KEY_INFO*)(pMsg->Data.p))->Key) 
//				{ 
//					case GUI_KEY_ESCAPE:
//								//LED1_TOGGLE;
//								GUI_EndDialog(hDlg, 0);
//								CreateFramewin();
//								break;
////		
//////						case GUI_KEY_ENTER:
//////								GUI_EndDialog(hDlg, 0);
//////								break;
//				}
//					break;
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}



/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/

WM_HWIN Create_XianGao_Process_Window(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)

//自定义消息函数
void _ChangeInfoText_1()//char * pStr
{
	//GUI_HWIN Thim;
//	WM_HWIN hDlg;
	//hDlg = pMsg->hWin;
  WM_MESSAGE Message;
  //Thim= WM_GetParent(CreateFramewin());
  Message.MsgId  = MSG_CHANGE_KEY;
  //Message.Data.p = pStr;
  //WM_SendMessage(WM_GetClientWindow( Create_XianGao_Process_Window()), &Message);
	WM_SendMessage(WM_GetClientWindow(Create_XianGao_Process_Window()), &Message);
  //WM_InvalidateWindow(WM_HBKWIN);
}

void _ChangeInfoText_2()//char * pStr
{
	//GUI_HWIN Thim;
//	WM_HWIN hDlg;
	//hDlg = pMsg->hWin;
  WM_MESSAGE Message;
//	Message.hWinSrc = ID_WINDOW_1;
  //Thim= WM_GetParent(CreateFramewin());
  Message.MsgId  = MSG_CHANGE_KEY1;
  //Message.Data.p = pStr;
  WM_SendMessage(WM_GetClientWindow( Create_XianGao_Process_Window()), &Message);
 // WM_InvalidateWindow(WM_HBKWIN);
}
// USER END

/*************************** End of file ****************************/
